[package]
name = "uno"
version = "0.1.0"
authors = ["Alex van der Heijden <vdhalex@gmail.com>"]
edition = "2018"

[dependencies]
thiserror = "1.0"
lazy_static = "1.4.0"
rand = "0.7.3"
uuid = { version = "0.8", features = ["serde", "v4"] }